services:
  backend:
    image: 197304876963.dkr.ecr.eu-north-1.amazonaws.com/genmemes/backend:latest
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - /home/ubuntu/app/uploads:/app/uploads
  frontend:
    image: 197304876963.dkr.ecr.eu-north-1.amazonaws.com/genmemes/frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
